# permissions for end users to view nodeunits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeunit-viewer-role
rules:
- apiGroups:
  - site.superedge.io
  resources:
  - nodeunits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - site.superedge.io
  resources:
  - nodeunits/status
  verbs:
  - get
