/*
Copyright 2021 The SuperEdge authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/attlee-wang/sites-manager/apis/site/v1"
	scheme "github.com/attlee-wang/sites-manager/pkg/util/site/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeUnitListsGetter has a method to return a NodeUnitListInterface.
// A group's client should implement this interface.
type NodeUnitListsGetter interface {
	NodeUnitLists(namespace string) NodeUnitListInterface
}

// NodeUnitListInterface has methods to work with NodeUnitList resources.
type NodeUnitListInterface interface {
	Create(ctx context.Context, nodeUnitList *v1.NodeUnitList, opts metav1.CreateOptions) (*v1.NodeUnitList, error)
	Update(ctx context.Context, nodeUnitList *v1.NodeUnitList, opts metav1.UpdateOptions) (*v1.NodeUnitList, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.NodeUnitList, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NodeUnitListList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NodeUnitList, err error)
	NodeUnitListExpansion
}

// nodeUnitLists implements NodeUnitListInterface
type nodeUnitLists struct {
	client rest.Interface
	ns     string
}

// newNodeUnitLists returns a NodeUnitLists
func newNodeUnitLists(c *SiteV1Client, namespace string) *nodeUnitLists {
	return &nodeUnitLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeUnitList, and returns the corresponding nodeUnitList object, and an error if there is any.
func (c *nodeUnitLists) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NodeUnitList, err error) {
	result = &v1.NodeUnitList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeunitlists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeUnitLists that match those selectors.
func (c *nodeUnitLists) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NodeUnitListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeUnitListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodeunitlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeUnitLists.
func (c *nodeUnitLists) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodeunitlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeUnitList and creates it.  Returns the server's representation of the nodeUnitList, and an error, if there is any.
func (c *nodeUnitLists) Create(ctx context.Context, nodeUnitList *v1.NodeUnitList, opts metav1.CreateOptions) (result *v1.NodeUnitList, err error) {
	result = &v1.NodeUnitList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodeunitlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeUnitList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeUnitList and updates it. Returns the server's representation of the nodeUnitList, and an error, if there is any.
func (c *nodeUnitLists) Update(ctx context.Context, nodeUnitList *v1.NodeUnitList, opts metav1.UpdateOptions) (result *v1.NodeUnitList, err error) {
	result = &v1.NodeUnitList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodeunitlists").
		Name(nodeUnitList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeUnitList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeUnitList and deletes it. Returns an error if one occurs.
func (c *nodeUnitLists) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeunitlists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeUnitLists) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodeunitlists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeUnitList.
func (c *nodeUnitLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NodeUnitList, err error) {
	result = &v1.NodeUnitList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodeunitlists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
