/*
Copyright 2021 The SuperEdge authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	sitev1 "github.com/attlee-wang/sites-manager/apis/site/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeUnitLists implements NodeUnitListInterface
type FakeNodeUnitLists struct {
	Fake *FakeSiteV1
	ns   string
}

var nodeunitlistsResource = schema.GroupVersionResource{Group: "site.superedge.io", Version: "v1", Resource: "nodeunitlists"}

var nodeunitlistsKind = schema.GroupVersionKind{Group: "site.superedge.io", Version: "v1", Kind: "NodeUnitList"}

// Get takes name of the nodeUnitList, and returns the corresponding nodeUnitList object, and an error if there is any.
func (c *FakeNodeUnitLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *sitev1.NodeUnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodeunitlistsResource, c.ns, name), &sitev1.NodeUnitList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sitev1.NodeUnitList), err
}

// List takes label and field selectors, and returns the list of NodeUnitLists that match those selectors.
func (c *FakeNodeUnitLists) List(ctx context.Context, opts v1.ListOptions) (result *sitev1.NodeUnitListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodeunitlistsResource, nodeunitlistsKind, c.ns, opts), &sitev1.NodeUnitListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sitev1.NodeUnitListList), err
}

// Watch returns a watch.Interface that watches the requested nodeUnitLists.
func (c *FakeNodeUnitLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodeunitlistsResource, c.ns, opts))

}

// Create takes the representation of a nodeUnitList and creates it.  Returns the server's representation of the nodeUnitList, and an error, if there is any.
func (c *FakeNodeUnitLists) Create(ctx context.Context, nodeUnitList *sitev1.NodeUnitList, opts v1.CreateOptions) (result *sitev1.NodeUnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodeunitlistsResource, c.ns, nodeUnitList), &sitev1.NodeUnitList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sitev1.NodeUnitList), err
}

// Update takes the representation of a nodeUnitList and updates it. Returns the server's representation of the nodeUnitList, and an error, if there is any.
func (c *FakeNodeUnitLists) Update(ctx context.Context, nodeUnitList *sitev1.NodeUnitList, opts v1.UpdateOptions) (result *sitev1.NodeUnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodeunitlistsResource, c.ns, nodeUnitList), &sitev1.NodeUnitList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sitev1.NodeUnitList), err
}

// Delete takes name of the nodeUnitList and deletes it. Returns an error if one occurs.
func (c *FakeNodeUnitLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodeunitlistsResource, c.ns, name), &sitev1.NodeUnitList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeUnitLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodeunitlistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &sitev1.NodeUnitListList{})
	return err
}

// Patch applies the patch and returns the patched nodeUnitList.
func (c *FakeNodeUnitLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sitev1.NodeUnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodeunitlistsResource, c.ns, name, pt, data, subresources...), &sitev1.NodeUnitList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sitev1.NodeUnitList), err
}
